import test from 'node:test';
import assert from 'node:assert/strict';
import { decimal, recalculateReagents, rowAmount, solutionMoles, theoreticalMass, columnEstimate, convertConcentration, rfValue, weighTubes } from '../src/domain/chemistry.js';
import { deriveExperiment, duration, changedFields, mergePatch, validateImport } from '../src/domain/experiment.js';
const close = (actual, expected) => assert.ok(Math.abs(actual - expected) < 1e-9, `${actual} != ${expected}`);
const reagent = { id: 'r1', type: 'starting_material', mw: '100', purity: '100', actualMass: '1', isLimiting: true };
const exp = { id: 'TEST', code: 'T', title: 'Test', units: { mass: 'g', mole: 'mol' }, stoichiometry: [reagent], targetMolecule: { molecularWeight: '200' }, columnAndYield: { eppendorfYield: { tubes: [{ id: 't', tareMass: '1', grossMass: '2.6', tag: 'spc' }] } } };

test('strict decimal comma and malformed input', () => { assert.equal(decimal('1,25'), 1.25); assert.ok(Number.isNaN(decimal('1.2.3', NaN))); assert.ok(Number.isNaN(decimal('Infinity', NaN))); });
test('purity zero is zero, not 100%', () => assert.equal(rowAmount({ ...reagent, purity: '0' }).mol, 0));
test('invalid purity reports an error', () => assert.ok(rowAmount({ ...reagent, purity: '101' }).error));
test('small scale remains precise', () => close(rowAmount({ ...reagent, actualMass: '0.0004' }).mol, 0.000004));
test('g/mol and mg/mmol yield same physical amount', () => { close(rowAmount(reagent).mol, rowAmount({ ...reagent, actualMass: '1000' }, { mass: 'mg' }).mol); assert.equal(recalculateReagents([{ ...reagent, actualMass: '1000' }], { mass: 'mg', mole: 'mmol' })[0].moles, 10); });
test('mismatched display units are explicit', () => assert.equal(recalculateReagents([reagent], { mass: 'g', mole: 'mmol' })[0].moles, 10));
test('change reference among three rows', () => { const rows = [reagent, { ...reagent, id: 'r2', actualMass: '2', isLimiting: false }, { ...reagent, id: 'r3', actualMass: '.5', isLimiting: false }]; assert.deepEqual(recalculateReagents(rows).map((r) => r.eq), [1, 2, .5]); assert.deepEqual(recalculateReagents(rows.map((r) => ({ ...r, isLimiting: r.id === 'r2' }))).map((r) => r.eq), [.5, 1, .25]); });
test('zero reference never returns nonfinite Eq', () => assert.ok(recalculateReagents([{ ...reagent, actualMass: '0' }]).every((r) => Number.isFinite(r.eq))));
test('explicit mass source prevents stale volume resurrection', () => assert.equal(rowAmount({ ...reagent, actualMass: '', actualVolume: '5', density: '1', amountSource: 'mass' }).mol, 0));
test('NaOH 2M 5mL gives 10 mmol', () => close(solutionMoles({ concUnit: 'CM', concentration: '2', actualVolume: '5' }).mol, .01));
test('HCl w/w and w/v differ correctly', () => { const row = { concUnit: 'C%', concentration: '10', actualVolume: '5', mw: '36.46', density: '1.05' }; close(solutionMoles({ ...row, concentrationBasis: 'w/w' }).mol, .525 / 36.46); close(solutionMoles({ ...row, concentrationBasis: 'w/v' }).mol, .5 / 36.46); assert.ok(solutionMoles(row).error); });
test('normality needs reaction n factor', () => { const row = { concUnit: 'N', concentration: '1', actualVolume: '10' }; assert.ok(solutionMoles(row).error); close(solutionMoles({ ...row, nFactor: '2' }).mol, .005); });
test('theoretical yield handles stoichiometric coefficients', () => close(theoreticalMass(.02, 200, { mass: 'g', mole: 'mol' }, 2, 1), 2));
test('theoretical yield handles mixed units', () => { close(theoreticalMass(10, 200, { mass: 'g', mole: 'mmol' }), 2); close(theoreticalMass(.01, 200, { mass: 'mg', mole: 'mol' }), 2000); });
test('SPC separate from SPP, assay distinct from HPLC area%', () => { const input = structuredClone(exp); input.columnAndYield.eppendorfYield.tubes.push({ id: 'by', tag: 'spp', tareMass: '1', grossMass: '1.2' }); Object.assign(input.columnAndYield.eppendorfYield, { purityHplc: '50', assayMassPercent: '90', assayBasis: 'mass' }); const y = deriveExperiment(input).columnAndYield.eppendorfYield; close(y.yieldPercent, 80); close(y.assayYieldPercent, 72); close(y.byproductMass, .2); });
test('yield updates without mounting the column component', () => { const input = structuredClone(exp); input.targetMolecule.molecularWeight = '250'; close(deriveExperiment(input).columnAndYield.eppendorfYield.yieldPercent, 64); });
test('gross below tare is visible error', () => assert.ok(weighTubes([{ tareMass: '2', grossMass: '1' }])[0].weighingError));
test('rederive ignores forged productMass', () => { const input = structuredClone(exp); input.columnAndYield.eppendorfYield.tubes[0].productMass = '999'; close(deriveExperiment(input).columnAndYield.eppendorfYield.productMass, 1.6); });
test('corrected 0/1-second durations are authoritative', () => { for (const seconds of [0, 1, 2]) assert.equal(duration({ startTime: '2026-10-01T00:00:00Z', endTime: '2026-10-01T02:00:00Z', durationSeconds: seconds }), seconds); });
test('legacy interval without duration recovers elapsed', () => assert.equal(duration({ startTime: '2026-10-01T00:00:00Z', endTime: '2026-10-01T02:00:00Z' }), 7200));
test('timer total equals intervals, stale total ignored', () => assert.equal(deriveExperiment({ ...exp, reactionTimer: { totalSeconds: 7200, intervals: [{ durationSeconds: 3600 }] } }).reactionTimer.totalSeconds, 3600));
test('legacy total preserved as explicit migrated interval', () => assert.equal(deriveExperiment({ ...exp, reactionTimer: { totalSeconds: 7200, intervals: [] } }).reactionTimer.totalSeconds, 7200));
test('Rf endpoints and physical bounds', () => { close(rfValue(2, 5), .4); assert.equal(rfValue(0, 5), 0); assert.equal(rfValue(2, 0), null); assert.equal(rfValue(6, 5), null); });
test('column geometry and CV model', () => { const r = columnEstimate({ diameterCm: 2, bedHeightCm: 30, voidFraction: .4, rfProduct: .25, rfImpurity: .5, fractionMl: 10, endCV: 8 }); close(r.bedMl, Math.PI * 30); close(r.cvProduct, 4); close(r.deltaCV, 2); assert.equal(r.fractions, 31); });
test('column rejects Rf zero instead of Infinity', () => assert.ok(columnEstimate({ rfProduct: 0 }).error));
test('nested patch preserves independent fields', () => { const before = { module: { a: 1, b: 2 } }; const patch = changedFields(before, { module: { a: 3, b: 2 } }); assert.deepEqual(mergePatch({ module: { a: 1, b: 4 } }, patch), { module: { a: 3, b: 4 } }); });
test('import rejects duplicate IDs, malformed numeric values, remote TLC images', () => { assert.throws(() => validateImport([exp, exp])); assert.throws(() => validateImport([{ ...exp, stoichiometry: [{ ...reagent, actualMass: '1.2.3' }] }])); assert.throws(() => validateImport([{ ...exp, tlcTimeline: [{ images: { uv254: 'https://example.invalid/image.jpg' } }] }])); });
test('prototype keys cannot be imported', () => assert.throws(() => validateImport(JSON.parse('[{"id":"A","code":"A","title":"A","__proto__":{}}]'))));
test('fractions keep physical numbering and ownership consistency', () => { const input = structuredClone(exp); input.columnAndYield.fractions = [{ number: 4 }, { number: 7 }]; input.columnAndYield.fractionGroups = [{ id: 'A', fractionNumbers: [4, 7] }, { id: 'B', fractionNumbers: [4] }]; const col = deriveExperiment(input).columnAndYield; assert.deepEqual(col.fractions.map((f) => f.number), [4, 7]); assert.equal(col.fractionGroups.length, 1); assert.equal(col.fractions[0].group, 'A'); });


test('scientific numbers survive rederive at nanomole scale', () => { const input = structuredClone(exp); input.stoichiometry[0].actualMass = '1e-8'; const derived = deriveExperiment(input); assert.ok(Math.abs(derived.stoichiometry[0].moles / 1e-10 - 1) < 1e-12); assert.ok(Math.abs(deriveExperiment(derived).columnAndYield.eppendorfYield.theoreticalYield / 2e-8 - 1) < 1e-12); });
test('concentration conversions preserve moles across M, %, N and basis', () => { let row = { concentration: '2', concUnit: 'CM', concentrationBasis: 'w/w', actualVolume: '5', mw: '40', density: '1.05', nFactor: '2' }; const mol = solutionMoles(row).mol; for (const [unit, basis] of [['C%', 'w/w'], ['C%', 'w/v'], ['N', 'w/v'], ['CM', 'w/v']]) { const converted = convertConcentration(row, unit, basis); assert.ok(!converted.error); row = { ...row, ...converted }; close(solutionMoles(row).mol, mol); } });
test('concentration conversion refuses missing density or z', () => { assert.ok(convertConcentration({ concUnit: 'CM', concentration: '2', mw: '40' }, 'C%', 'w/w').error); assert.ok(convertConcentration({ concUnit: 'CM', concentration: '2' }, 'N').error); });
test('500 repeated unit conversions do not round away small quantities', () => { let grams = 0.0000000143; for (let i = 0; i < 500; i++) grams = grams * 1000 / 1000; assert.ok(Math.abs(grams - 0.0000000143) < 1e-20); assert.equal(rowAmount({ ...reagent, actualMass: String(grams) }).mol, grams / 100); });
test('catalyst is never selected as limiting reagent', () => { const rows = recalculateReagents([{ ...reagent, type: 'catalyst' }, { ...reagent, id: 'r2', type: 'reagent', isLimiting: false }]); assert.equal(rows.find((r) => r.isLimiting).id, 'r2'); });
test('manual crude total survives while tube mode remains authoritative', () => { const input = { ...exp, workup: { crudeMassSource: 'manual', crudeMass: '1.25', crudeTubes: [{ tareMass: '1', grossMass: '3' }] } }; assert.equal(deriveExperiment(input).workup.crudeMass, 1.25); assert.equal(deriveExperiment({ ...input, workup: { ...input.workup, crudeMassSource: 'tubes' } }).workup.crudeMass, 2); });
test('TLC timestamp is preserved by unrelated recalculation', () => { const input = { ...exp, tlcTimeline: [{ id: 'tlc', timestamp: '2026-09-28T01:00:00Z' }] }; assert.equal(deriveExperiment(input).tlcTimeline[0].timestamp, input.tlcTimeline[0].timestamp); });
test('discarded physical tubes cannot retain group ownership', () => { const input = { ...exp, columnAndYield: { fractions: [{ number: 4, discarded: true }, { number: 7 }], fractionGroups: [{ id: 'A', fractionNumbers: [4, 7] }] } }; const col = deriveExperiment(input).columnAndYield; assert.deepEqual(col.fractionGroups[0].fractionNumbers, [7]); assert.equal(col.fractions[0].group, null); });

test('explicit zero product MW does not reuse stale legacy MW', () => { const input = structuredClone(exp); input.targetMolecule.molecularWeight = '0'; input.columnAndYield.eppendorfYield.targetMW = '200'; assert.equal(deriveExperiment(input).columnAndYield.eppendorfYield.theoreticalYield, 0); });
test('import rejects overlapping pools and duplicate physical tubes', () => { assert.throws(() => validateImport([{ ...exp, columnAndYield: { fractions: [{ number: 4 }, { number: 4 }] } }])); assert.throws(() => validateImport([{ ...exp, columnAndYield: { fractions: [{ number: 4 }], fractionGroups: [{ fractionNumbers: [4] }, { fractionNumbers: [4] }] } }])); });

test('malformed amount and missing liquid density produce actionable errors', () => { assert.ok(rowAmount({ ...reagent, amountSource: 'mass', actualMass: '1.2.3' }).error); assert.ok(rowAmount({ ...reagent, amountSource: 'volume', actualVolume: '5', density: '0' }).error); });
