import 'fake-indexeddb/auto';
import test from 'node:test';
import assert from 'node:assert/strict';
const memory = () => { const values = new Map(); return { getItem: (k) => values.get(k) || null, setItem: (k, v) => values.set(k, String(v)), removeItem: (k) => values.delete(k) }; };
globalThis.localStorage = memory(); globalThis.sessionStorage = memory();
Object.defineProperty(globalThis.navigator, 'onLine', { value: true, configurable: true });
const backend = await import('../src/services/demoBackend.js');
const { deriveExperiment, changedFields } = await import('../src/domain/experiment.js');
const user = backend.selectDemoUser('demo-researcher-a');
const make = (id = crypto.randomUUID()) => deriveExperiment({ id, code: 'QA', title: 'QA', creatorId: user.uid, units: { mass: 'g', mole: 'mol' }, stoichiometry: [], reactionTimer: { intervals: [] }, columnAndYield: { fractions: [] } });
const save = (base, fields) => backend.saveExperimentData({ ...base, ...fields }, { base, patch: changedFields(base, { ...base, ...fields }) });

test('local backend transactional lifecycle and isolation', async (t) => {
  let original;
  await t.test('create acknowledges actual durable record', async () => { const result = await backend.saveExperimentData(make()); assert.equal(result.success, true); assert.equal(result.data.revision, 1); original = result.data; });
  await t.test('UID owner cannot be impersonated', async () => { const result = await backend.saveExperimentData({ ...original, creatorId: 'demo-researcher-b' }); assert.equal(result.success, false); });
  await t.test('independent stale field patches merge', async () => { const a = await save(original, { title: 'new title' }); assert.equal(a.success, true); const b = await save(original, { labRoom: 'room B' }); assert.equal(b.success, true); assert.equal(b.data.title, 'new title'); assert.equal(b.data.labRoom, 'room B'); original = b.data; });
  await t.test('conflicting stale field patch rejected with durable draft', async () => { const a = await save(original, { title: 'latest' }); assert.equal(a.success, true); const b = await save(original, { title: 'stale overwrite' }); assert.equal(b.success, false); await backend.discardDemoDrafts(original.id); original = a.data; });
  await t.test('offline draft survives fresh subscription and replays', async () => { backend.setDemoOffline(true); const result = await save(original, { notes: 'offline durable text' }); assert.equal(result.pending, true); const snapshot = await new Promise((resolve) => { const unsubscribe = backend.loadExperimentsData((list) => { unsubscribe(); resolve(list); }, user.uid); }); assert.equal(snapshot.find((e) => e.id === original.id).notes, 'offline durable text'); backend.setDemoOffline(false); await backend.retryDemoDrafts(); });
  await t.test('trash blocks stale resurrection', async () => { const e = (await backend.saveExperimentData(make())).data; const trashed = await backend.saveExperimentData({ ...e, inTrash: true }, { base: e, patch: { inTrash: true }, kind: 'trash' }); assert.equal(trashed.success, true); assert.equal((await save(e, { notes: 'old tab' })).success, false); await backend.discardDemoDrafts(e.id); assert.equal((await backend.deleteExperimentData(e.id)).success, true); assert.equal((await save(e, { notes: 'old tab after purge' })).success, false); await backend.discardDemoDrafts(e.id); });
  await t.test('permanent delete requires trash and is atomic', async () => { const a = (await backend.saveExperimentData(make())).data, b = (await backend.saveExperimentData(make())).data; await backend.saveExperimentData({ ...a, inTrash: true }, { base: a, patch: { inTrash: true }, kind: 'trash' }); assert.equal((await backend.permanentlyDeleteExperimentsBatch([a.id, b.id])).success, false); const result = await backend.saveExperimentData({ ...a, inTrash: false }, { base: { ...a, inTrash: true, revision: 2 }, patch: { inTrash: false }, kind: 'restore' }); assert.equal(result.success, true); });
  await t.test('concurrent retry commits a durable draft only once', async () => { const e = (await backend.saveExperimentData(make())).data; backend.setDemoOffline(true); await save(e, { notes: 'only once' }); backend.setDemoOffline(false); await Promise.all([backend.retryDemoDrafts(), backend.retryDemoDrafts()]); const list = await new Promise((resolve) => { const unsub = backend.loadExperimentsData((items) => { unsub(); resolve(items); }, user.uid); }); const record = list.find((item) => item.id === e.id); assert.equal(record.revision, 2); assert.equal(record.auditTrail.length, 2); assert.ok(!record.demoPending); });
  await t.test('stale draft cannot visually resurrect trash or tombstone', async () => { const e = (await backend.saveExperimentData(make())).data; await backend.saveExperimentData({ ...e, inTrash: true }, { base: e, patch: { inTrash: true }, kind: 'trash' }); await save(e, { notes: 'stale tab' }); const snapshot = () => new Promise((resolve) => { const unsub = backend.loadExperimentsData((items) => { unsub(); resolve(items); }, user.uid); }); assert.equal((await snapshot()).find((item) => item.id === e.id).inTrash, true); await backend.deleteExperimentData(e.id); await save(e, { notes: 'stale tab after purge' }); assert.ok(!(await snapshot()).some((item) => item.id === e.id)); await backend.discardDemoDrafts(e.id); });
  await t.test('user B cannot read user A records', async () => { backend.selectDemoUser('demo-researcher-b'); const list = await new Promise((resolve) => { const unsubscribe = backend.loadExperimentsData((items) => { unsubscribe(); resolve(items); }, 'demo-researcher-b'); }); assert.equal(list.length, 0); assert.equal((await backend.deleteExperimentData(original.id)).success, false); backend.selectDemoUser(user.uid); });
});
